server:
  port: 8081

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/smartlogix
    username: postgres
    password: v8biturbo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET:SmartLogixSuperSecretKeyForJWT2024PlatformMicroservicesArchitecture!!}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/